package com.nanotweets.dao.model;

import com.nanotweets.dao.model.Annotation;
import com.nanotweets.dao.model.AnnotationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnnotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int countByExample(AnnotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int insert(Annotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int insertSelective(Annotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    List<Annotation> selectByExample(AnnotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    Annotation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Annotation record, @Param("example") AnnotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Annotation record, @Param("example") AnnotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Annotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.annotation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Annotation record);
}